
services:
  - type: web
    name: django-api
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn arabic_kids_app.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: arabic_kids_app.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
