# Generated by Django 5.1.7 on 2025-05-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterchoice',
            name='letter',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
