# Generated by Django 5.2.4 on 2025-07-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_letterchoice_letter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='letter',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question_type',
            field=models.CharField(max_length=20),
        ),
    ]
