# Generated by Django 5.1.7 on 2025-07-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_timestamp_useranswer_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordimagematch',
            name='category',
            field=models.CharField(default='fruits', max_length=50),
            preserve_default=False,
        ),
    ]
